name: Run Tests

on: 
  push:
    branches:
    - master
    - main
  
jobs:  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17, 18, 20]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci && npm test -w ocfl -w ocfl-fs
